services:
  app:
    build: .
    image: yeonukim/nextjs_deploy_tutorial:latest
    container_name: nextjs_app
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://nextjs_app:3000']
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      app:
        condition: service_healthy
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - mynetwork

networks:
  mynetwork:
